### ISSUE TITLE
Getting `/usr/bin/env: invalid option -- 'S'` when I run `athenna new`

### ISSUE THREAD

**Issue by emuthomi** [AthennaIO/Cli#67]
### Version

latest

### Steps to reproduce

I followed the docs at https://athenna.io/docs/getting-started/installation and did `npm install -g @athenna/cli`

But then running `athenna new athenna-project --type http`shows the following error in terminal:

`/usr/bin/env: invalid option -- 'S'`

### Expected behavior

A new project created

### Actual behavior

error shown: `/usr/bin/env: invalid option -- 'S'`

### Environment

```Shell
System:
    OS: Linux 5.4 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.66 GB / 7.65 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 8.19.4 - /usr/local/bin/npm
```

**Comment by jlenon7** [comment]
How you doing @emuthomi? Thank you so much for opening this. Actually, we are having the same problem when running on Windows, as you can see at #66.

Strange is how the CI was not able to catch these errors, mainly in the Linux environment like yours. I'll take a look at it

**Comment by jlenon7** [comment]
I've merged a PR that might fix this issue, could you please try again mate?

**Comment by emuthomi** [comment]
> I've merged a PR that might fix this issue, could you please try again mate?

Thanks for the quick response. I'll run the script again and report back.

**Comment by emuthomi** [comment]
> I've merged a PR that might fix this issue, could you please try again mate?

Thanks for the quick response. I'll run the script again and report back.

**Comment by jlenon7** [comment]
And please don't rely on the current documentation. I really apologize for that, but the project is still under development, and I've done a lot of breaking changes in the packages and they had a LOT of improvements. I'm even rewriting the documentation using Next.js and the Dracula UI here: https://github.com/AthennaIO/Docs/tree/feat/move-to-next.

Your help would be very welcome here in the project, we have a lot of work ahead... If you want to join our community on Discord, this is the invite link: https://discord.gg/vaZgRUkMsm

There on Discord, I can guide you and help with whatever you need to contribute to any feature. And again, I apologize for the problems, and thank you very much for your report, I think I would have never seen it since I'm using MacOS heheh.

**Comment by emuthomi** [comment]
So everything went well. I will continue the exploration and report any other issue I face.

<pre><font color="#4E9A06">?</font> <b>Do you wish to create a Laravel project style?</b> <font color="#06989A">Yes</font>

<font color="#8AE234"><b>[ GENERATING HTTP SERVER ]</b></font>

<font color="#4E9A06">→</font> Clone scaffold project from <font color="#7628C8"><b>https://github.com/AthennaIO/AthennaIO.git</b></font> in branch <font color="#7628C8"><b>http</b></font> 5687ms
<font color="#4E9A06">→</font> Move project to your path 12ms
<font color="#CC0000">→</font> Install dependencies using <font color="#FCE94F"><b>npm</b></font> 149583ms 
<font color="#AAAAAA">→ Remove unnecessary files and create </font><font color="#A89B34"><b>.env</b></font><font color="#AAAAAA"> files</font>

<font color="#8AE234"><b>[  success  ]</b></font> Project successfully created.
<font color="#AAAAAA">╭────────────────────────────────────────────────╮</font>
<font color="#AAAAAA">│ </font><font color="#7628C8">    Run following commands to get started:    </font> │
<font color="#AAAAAA">├────────────────────────────────────────────────┤</font>
<font color="#AAAAAA">│                                                │</font>
<font color="#AAAAAA">│     ❯ cd athenna-project                       │</font>
<font color="#AAAAAA">│     ❯ ./node artisan test                      │</font>
<font color="#AAAAAA">│     ❯ ./node artisan serve                     │</font>
<font color="#AAAAAA">│                                                │</font>
<font color="#AAAAAA">╰────────────────────────────────────────────────╯</font>
</pre>
